/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exorpg;

import exorpg.RPG.*;

public class App {


    public static void main(String[] args) {
        Personnage paul = new Personnage("Jean-Paul");
        Personnage[] monstres = new Personnage[2];

        paul.setPv(100);
        paul.setForce(10);
        
        monstres[0] = new Personnage("Slime", 25, 3);
        monstres[0].setArmor(new Armure("Aucune", 0));
        monstres[0].setEquipedWeapon(new Arme("Crachat", 2, 0.1f));

        monstres[1] = new Personnage("Gobelin", 30, 6);
        monstres[1].setArmor(new Armure("Côte de maill", 15));
        monstres[1].setEquipedWeapon(new Arme("Dague", 10, 0.05f));

        System.out.println("Vous incarnez le héro suivant "+paul);
        System.out.println("Il a "+paul.getForce()+" Force");

        Arme epee = new Arme("Epee rouillée", 10, 0.2f);
        Armure carton = new Armure("Cartons sctochés", 10);

        paul.setArmor(carton);
        paul.setEquipedWeapon(epee);

        Personnage toto = new Personnage("Toto");
        toto.setArmor(carton);

        int i = 0;
        for (Personnage personnage : monstres) {
            combattre(paul, personnage);
            System.out.println(i++);
        }

    }

    public static void combattre(Personnage p1, Personnage p2){
        int i = 0;
        while(p1.getPv() > 0 && p2.getPv() > 0){
            if(i % 2 == 0)
                p1.attaquer(p2);
            else
                p2.attaquer(p1);
            i++;
        }

        System.out.println("Le vainqueur est : "+((p1.getPv()>0) ? p1 : p2));
    }
}
